apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: users
spec:
  hosts:
    - "users"
  http:
    - match:
        - headers:
            env:
              exact: rune
      route:
        - destination:
            host: users
            subset: green
    - route:
      - destination:3
          host: users
          subset: blue

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: users
spec:
  host: users
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
    - name: blue
      labels:
        version: "1"
    - name: green
      labels:
        version: "2"