apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
    - port: 8081
      name: grpc
      protocol: TCP
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-1
  labels:
    app: users-1
spec:
  replicas: 1
  template:
    metadata:
      name: users
      labels:
        app: users
        version: "1"
    spec:
      containers:
        - name: users
          image: dr0l3/grpc-users
          ports:
            - containerPort: 8081
              name: grpc
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: users
      version: "1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-2
  labels:
    app: users-2
spec:
  replicas: 1
  template:
    metadata:
      name: users
      labels:
        app: users
        version: "2"
    spec:
      containers:
        - name: users
          image: dr0l3/grpc-users
          ports:
            - containerPort: 8081
              name: grpc
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: users
      version: "2"
