apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: users
spec:
  hosts:
    - "users"
  http:
    - match:
        - port: 8081
      route:
        - destination:
            host: users
            subset: blue
          weight: 90
        - destination:
            host: users
            subset: green
          weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: users
spec:
  host: users
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
    - name: blue
      labels:
        version: "1"
    - name: green
      labels:
        version: "2"