apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      name: http
      protocol: TCP
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: dr0l3/grpc-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: USER_ADRESS
              value: "users"
            - name: CONVERSATION_ADRESS
              value: "conversations"
            - name: MESSAGES_ADDRESS
              value: "messages"
            - name: ORCHESTATOR_ADDRESS
              value: "orchestrator"
            - name: JAEGER_SERVICE_NAME
              value: "gateway"
      restartPolicy: Always
  selector:
    matchLabels:
      app: gateway
