apiVersion: v1
kind: Service
metadata:
  name: messages
spec:
  selector:
    app: messages
  ports:
    - port: 8082
      name: grpc
      protocol: TCP
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-1
  labels:
    app: messages-1
spec:
  replicas: 1
  template:
    metadata:
      name: messages
      labels:
        app: messages
        version: "1"
    spec:
      containers:
        - name: messages
          image: dr0l3/grpc-messages
          ports:
            - containerPort: 8082
              name: grpc
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: messages
      version: "1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-2
  labels:
    app: messages-2
spec:
  replicas: 0
  template:
    metadata:
      name: messages
      labels:
        app: messages
        version: "2"
    spec:
      containers:
        - name: messages
          image: dr0l3/grpc-messages
          ports:
            - containerPort: 8082
              name: grpc
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: messages
      version: "2"
